project:
  type: book
  output-dir: docs
  
book:
  title: "MATH 60602 - Analyse multidimensionnelle appliquée"
  author: 
  - name: "Denis Larocque"
  - name: "Léo Belzile"
  date: "avril 2022"
  description: | 
      Cours MATH 60602 - Analyse multidimensionnelle appliquée à HEC Montréal.
  chapters:
    - index.qmd
    - 01-analyseexploratoire.qmd
    - 02-analysefactorielle.qmd
    - 03-regroupements.qmd
    - 04-selectionmodeles.qmd
    - 05-reglogistique.qmd
    - 06-survie.qmd
    - 07-donneesmanquantes.qmd
  site-url: https://lbelzile.github.io/math60602/
  repo-url: https://github.com/lbelzile/math60602/
  repo-branch: master
  repo-actions: [edit]
  search: true
  downloads: [pdf, epub]
  bibliography: math60602.bib
  css: css/style.css
  fontsize: 1.4em
  highlight: tango
  toc_depth: 2
  split_bib: no
format:
  html:
    theme: cosmo
    license: "Tous droits réservés"
    fig-align: center
    toc-location: right
    code-fold: true
    code-summary: "Code"
    code-overflow: wrap
    code-block-border-left: true
    code-copy: true
  pdf:
    documentclass: scrreport
    fontsize: 11pt
    papersize: letter
    toc-title: "Table des matières"
    include-in-header: preamble.tex
    pdf-engine: pdflatex
    citation-package: natbib
    keep-tex: true
    fig-pos: 't'
    biblio-style: apalike2
    link-citations: yes
  epub:
    number-depth: 2
