project:
  type: book
  output-dir: docs
execute: 
  cache: true
  freeze: auto

book:
  title: "MATH 60602 - Analyse multidimensionnelle appliquée"
  output-file: "MATH60602"
  author: 
  - name: "Denis Larocque"
  - name: "Léo Belzile"
  page-footer: "Tous droits réservés (Denis Larocque, Léo Belzile)" 
  date: "septembre 2022"
  description: | 
      MATH 60602 - Analyse multidimensionnelle appliquée, HEC Montréal.
  chapters:
    - index.qmd
    - 01-analyseexploratoire.qmd
    - 02-analysefactorielle.qmd
    - 04-selectionmodeles.qmd
    - 05-reglogistique.qmd
    - 06-survie.qmd
    - 03-regroupements.qmd
    - 07-donneesmanquantes.qmd
  site-url: https://lbelzile.github.io/math60602/
  repo-url: https://github.com/lbelzile/math60602/
  repo-branch: master
  repo-actions: [edit]
  search: true
  bibliography: math60602.bib, packages.bib
  css: css/style.css
  fontsize: 1.4em
  highlight: tango
  split_bib: no
  engine: knitr
format:
  html:
    theme: cosmo
    reader-mode: true
    license: "Tous droits réservés"
    fig-align: center
    toc-location: right
    code-fold: false
    code-summary: "Code"
    code-overflow: wrap
    code-block-border-left: true
    code-copy: true
    default-image-extension: png
    bibliography: math60602.bib
  pdf:
    documentclass: book
    latex_documents:
       targetname: MATH60602.tex
    fontsize: 11pt
    fig-pos: "ht!"
    papersize: letter
    toc-title: "Table des matières"
    include-in-header: preamble.tex
    pdf-engine: pdflatex
    citation-package: natbib
    keep-tex: true
    biblio-style: apalike2
    link-citations: yes
    default-image-extension: pdf

