# Programmation **R** {#programmation-R}

```{r}
#| label: setup
#| file: "_common.R"
#| include: true
#| echo: false
#| message: false
#| warning: false
```

## Visualisation et grammaire des graphiques

## Manipulation de bases de données

### Base de données volumineuses

Le langage de programmation **R** est souvent décrié pour son incapacité à gérer les bases de données volumineuses, en raison de leur stockage en mémoire vive et des copies faites lors de manipulation. 

Parmi les autres alternatives qui utilisent la même grammaire, figurent 
- `polar` avec l'extension [`tidypolars`](https://tidypolars.etiennebacher.com/) pour les bases de données Polars. Bâti sur Apache Arrow, évalue de manière paresseuse les requêtes en plus d'utiliser par défaut plusieurs coeurs (calcul en parallèle)
- [`DuckDB`](https://duckdb.org/) via [`duckplyr`](https://duckplyr.tidyverse.org/index.html), qui ressemble le plus à SQL
- Apache [`arrow`](https://arrow.apache.org/) pour gérer des fichiers Parquet, donc la compression est souvent plus élevée que des fichiers CSV et qui permet des requêtes rapides. Prend en charge les requêtes de `dplyr` directement.

Ces deux méthodes n'évaluent 
