<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="MATH 60602 - Analyse multidimensionnelle appliquée, HEC Montréal.">

<title>5&nbsp; Analyse de survie – MATH 60602 - Analyse multidimensionnelle appliquée</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./analysefactorielle.html" rel="next">
<link href="./reglogistique.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="css/style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./survie.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Analyse de survie</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MATH 60602 - Analyse multidimensionnelle appliquée</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lbelzile/math60602/" title="Code source" class="quarto-navigation-tool px-1" aria-label="Code source"><i class="bi bi-github"></i></a>
    <a href="./MATH60602.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analyseexploratoire.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Analyse exploratoire</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./selectionmodeles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sélection de variables et de modèles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reglogistique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Régression logistique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survie.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Analyse de survie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysefactorielle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Réduction de la dimension</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regroupements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analyse de regroupements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./donneesmanquantes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Données manquantes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Références</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rappel-regressionlineaire.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Régression linéaire</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#exemple-du-temps-dabonnement" id="toc-exemple-du-temps-dabonnement" class="nav-link" data-scroll-target="#exemple-du-temps-dabonnement"><span class="header-section-number">5.1.1</span> Exemple du temps d’abonnement</a></li>
  <li><a href="#contexte" id="toc-contexte" class="nav-link" data-scroll-target="#contexte"><span class="header-section-number">5.1.2</span> Contexte</a></li>
  </ul></li>
  <li><a href="#fonctions-de-survie-et-de-risque" id="toc-fonctions-de-survie-et-de-risque" class="nav-link" data-scroll-target="#fonctions-de-survie-et-de-risque"><span class="header-section-number">5.2</span> Fonctions de survie et de risque</a></li>
  <li><a href="#estimation-dune-courbe-de-survie-et-de-risque" id="toc-estimation-dune-courbe-de-survie-et-de-risque" class="nav-link" data-scroll-target="#estimation-dune-courbe-de-survie-et-de-risque"><span class="header-section-number">5.3</span> Estimation d’une courbe de survie et de risque</a>
  <ul class="collapse">
  <li><a href="#calcul-de-lestimateur-de-kaplanmeier" id="toc-calcul-de-lestimateur-de-kaplanmeier" class="nav-link" data-scroll-target="#calcul-de-lestimateur-de-kaplanmeier"><span class="header-section-number">5.3.1</span> Calcul de l’estimateur de Kaplan–Meier</a></li>
  </ul></li>
  <li><a href="#comparaison-de-deux-courbes-de-survie" id="toc-comparaison-de-deux-courbes-de-survie" class="nav-link" data-scroll-target="#comparaison-de-deux-courbes-de-survie"><span class="header-section-number">5.4</span> Comparaison de deux courbes de survie</a></li>
  <li><a href="#modèle-à-risques-proportionnels-de-cox" id="toc-modèle-à-risques-proportionnels-de-cox" class="nav-link" data-scroll-target="#modèle-à-risques-proportionnels-de-cox"><span class="header-section-number">5.5</span> Modèle à risques proportionnels de Cox</a>
  <ul class="collapse">
  <li><a href="#description-du-modèle-de-cox" id="toc-description-du-modèle-de-cox" class="nav-link" data-scroll-target="#description-du-modèle-de-cox"><span class="header-section-number">5.5.1</span> Description du modèle de Cox</a></li>
  <li><a href="#estimation-de-la-fonction-de-survie-pour-des-valeurs-particulières-des-variables-explicatives" id="toc-estimation-de-la-fonction-de-survie-pour-des-valeurs-particulières-des-variables-explicatives" class="nav-link" data-scroll-target="#estimation-de-la-fonction-de-survie-pour-des-valeurs-particulières-des-variables-explicatives"><span class="header-section-number">5.5.2</span> Estimation de la fonction de survie pour des valeurs particulières des variables explicatives</a></li>
  <li><a href="#variables-explicatives-dont-la-valeur-change-dans-le-temps" id="toc-variables-explicatives-dont-la-valeur-change-dans-le-temps" class="nav-link" data-scroll-target="#variables-explicatives-dont-la-valeur-change-dans-le-temps"><span class="header-section-number">5.5.3</span> Variables explicatives dont la valeur change dans le temps</a></li>
  <li><a href="#postulat-de-risques-proportionnels" id="toc-postulat-de-risques-proportionnels" class="nav-link" data-scroll-target="#postulat-de-risques-proportionnels"><span class="header-section-number">5.5.4</span> Postulat de risques proportionnels</a></li>
  <li><a href="#stratification" id="toc-stratification" class="nav-link" data-scroll-target="#stratification"><span class="header-section-number">5.5.5</span> Stratification</a></li>
  <li><a href="#modèle-non-proportionnel" id="toc-modèle-non-proportionnel" class="nav-link" data-scroll-target="#modèle-non-proportionnel"><span class="header-section-number">5.5.6</span> Modèle non-proportionnel</a></li>
  </ul></li>
  <li><a href="#modèle-à-risques-compétitifs" id="toc-modèle-à-risques-compétitifs" class="nav-link" data-scroll-target="#modèle-à-risques-compétitifs"><span class="header-section-number">5.6</span> Modèle à risques compétitifs</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/lbelzile/math60602/edit/master/survie.qmd" class="toc-action"><i class="bi bi-github"></i>Éditer cette page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="analyse-survie" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Analyse de survie</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>Cette section traite de temps avant qu’un événement survienne. Le traitement de ce type de données, dites données de survie en référence au domaine médical, est particulier parce que l’information disponible est incomplète. Plusieurs mécanismes peuvent impacter la survie: généralement les données sont sujettes à troncature et à censure.</p>
<p>Pour déterminer les mécanismes de survie en présence, il peut être utile de représenter le processus de collecte de données à l’aide d’un diagramme de Lexis: ce dernier présente la trajectoire observée à l’aide d’une droite de pente un. L’axe des abscisses (<span class="math inline">\(x\)</span>) donne le temps (au calendrier) et l’axe des ordonnées (<span class="math inline">\(y\)</span>) la durée observée.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lexis" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lexis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Lexis_censure.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lexis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Diagramme de Lexis pour données tronquées à gauche (<span class="math inline">\(A\)</span> et <span class="math inline">\(C\)</span>) et censurées à droite (<span class="math inline">\(C\)</span> et <span class="math inline">\(D\)</span>).
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-lexis" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> montre des courbes fictives. On trace une droite de pente 1 représentant la durée en fonction du temps (date au calendrier) et la fenêtre définit la période de collecte de donnée. La censure est indiquée par des cercles, les événements par des croix.</p>
<p>On parle de censure lorsque le temps réel de l’événement n’est pas observé (information partielle).</p>
<ul>
<li>Censure à droite: l’événement n’est pas encore survenu au temps <span class="math inline">\(t\)</span>: on sait que <span class="math inline">\(T &gt; t\)</span>.</li>
<li>Censure à gauche: l’événement survient avant le temps <span class="math inline">\(t\)</span>, donc la vraie valeur est inférieure à la valeur observée (<span class="math inline">\(T &lt; t\)</span>)</li>
<li>Censure par intervalle: l’événement est survenu dans la plage <span class="math inline">\([t_1, t_2]\)</span> (données arrondies)</li>
</ul>
<p>La censure peut être aléatoire (par exemple, une personne qui fait partie d’un protocole de rercherche déménage dans un autre pays parce que sa conjointe a trouvé un emploi là-bas et cette raison n’a aucun lien avec son état de santé). La censure administrative, un mécanisme déterministe qui survient lorsque les données sont collectées sur une période fixe de temps, ne fournit pas non plus d’information sur l’événement en question. On supposera dans ces notes que nous sommes dans un de ces deux cas de figure.</p>
<p>Si la censure est informative, les outils présentés ne sont pas adéquats! Par exemple, si un patient d’une étude clinique est déchargé d’un protocole médical car il est trop mal en point, cela nous renseigne sur son état de santé et sur sa survie.</p>
<p>La troncature, rarement discutée, est liée au processus de collecte et détermine quelles observations sont incluses dans l’étude. La plage des valeurs possibles est tronquée. Les types de troncature sont:</p>
<ul>
<li>troncature à gauche: le temps minimum est supérieur à <span class="math inline">\(t_0\)</span></li>
<li>troncature à droite: le temps maximum est inférieur à <span class="math inline">\(t_1\)</span></li>
<li>troncature par intervalle: le temps de l’événement doit survenir entre <span class="math inline">\(t_0\)</span> et <span class="math inline">\(t_1\)</span>.</li>
</ul>
<p>La troncature à gauche est la plus fréquente: elle survient par exemple si on étudie le temps d’abonnement, mais qu’on n’a accès qu’aux dossiers de clients et de clientes qui sont actifs dans le système. Ainsi, une personne qui se serait désabonnée une journée avant qu’on télécharge les données ne se trouvera pas dans la base de données. Si on ne tient pas compte de cet état de fait et des fantômes, nos estimations seront biaisées.</p>
<p>La troncature par intervalle survient quand on considère uniquement les personnes pour lesquelles l’événement d’intérêt est survenu. Si l’on s’intéresse à la durée de la relation d’emploi et seules les personnes à l’emploi qui ont pris leur retraite entre 2009 et 2021 sont considérées pour l’étude, on sera en présence de troncature par intervalle comme représenté dans la <a href="#fig-troncatureintervalle" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-troncatureintervalle" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-troncatureintervalle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/lexis_troncationintervalle.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-troncatureintervalle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Diagramme de Lexis illustrant la troncature par intervalle.
</figcaption>
</figure>
</div>
</div>
</div>
<p>On considère comme exemple une étude sur le chômage dû à la crise du coronavirus. On s’intéresse à tous ceux qui étaient en recherche active d’emploi entre mars et juin; seuls ceux qui étaient au chômage durant cette période seront considérés. Certaines personnes seront déjà au chômage en avril et donc leur durée de chômage en mars est déjà longue (troncature à gauche). Lors de notre suivi, d’autres personnes mentionneront avoir trouvé un emploi lors de notre appel, mais ne pourront nous renseigner sur la date exacte de leur embauche: cette dernière précèdera notre prise de contact, mais nous est inconnue (censure à gauche). D’autres personnes seront toujours au chômage en juin à la fin de l’étude et on ignorera le nombre réel de mois passés au chômage (censure à droite). Enfin, certaines personnes cesseront de chercher activement un emploi et donc quitteront l’étude (censure à droite). Tous ces méchanismes (complexes) peuvent être dictés par certaines covariables (employabilité, découragement) et être aléatoires ou pas. Pour estimer le taux de chômage, il faudra prendre en compte les méchanismes de survie dans notre modèle. On se concentrera sur le cas simple des données censurées à droite de façon aléatoire.</p>
<p>Avec la survie, les statistiques descriptives usuelles sont trompeuses. La figure de <a href="https://theconversation.com/music-to-die-for-how-genre-affects-popular-musicians-life-expectancy-36660">cet article tiré de <em>The Conversation</em></a> montre l’impact drastique de la censure en représentant l’âge moyen au décès en fonction du genre musical, ordonné par ordre d’apparition de ce dernier. Puisque seules les personnes décédées sont incluses, les artistes de hip-hop décédés l’ont été forcément en bas-âge. Si on ne prend pas en compte la censure, on obtiendrait une conclusion erronnée.</p>
<section id="exemple-du-temps-dabonnement" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="exemple-du-temps-dabonnement"><span class="header-section-number">5.1.1</span> Exemple du temps d’abonnement</h3>
<p>Une entreprise oeuvrant dans le secteur des télécommunications s’intéresse aux facteurs influençant le temps qu’un client reste abonné à son service de téléphone cellulaire. Des données provenant d’un échantillon de clients se trouvent dans le fichier <code>survie1</code>, qui contient les variables suivantes:</p>
<ul>
<li><span class="math inline">\(\texttt{temps}\)</span>: temps (en semaines) que le client est resté abonné au service de téléphone cellulaire. Il s’agit du vrai temps si le client n’est plus abonné et d’un temps censuré à droite si le client est toujours abonné.</li>
<li><span class="math inline">\(\texttt{censure}\)</span>: variable binaire qui indique si la variable <span class="math inline">\(\texttt{t}\)</span> est censurée (<span class="math inline">\(0\)</span> si le client est toujours abonné) ou non (<span class="math inline">\(1\)</span>, la variable <span class="math inline">\(\texttt{t}\)</span> est la durée finale de l’abonnement).</li>
<li><span class="math inline">\(\texttt{age}\)</span>: âge du client au début de l’abonnement.</li>
<li><span class="math inline">\(\texttt{sexe}\)</span>: sexe du client, soit femme (<span class="math inline">\(1\)</span>), soit homme (<span class="math inline">\(0\)</span>).</li>
<li><span class="math inline">\(\texttt{service}\)</span>: nombre de services en plus du cellulaire auquel le client est abonné parmi internet, téléphone fixe, télévision (câble ou antenne parabolique).</li>
<li><span class="math inline">\(\texttt{region}\)</span>: région où habite le client en ce moment (valeurs entre 1 et 5).</li>
</ul>
</section>
<section id="contexte" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="contexte"><span class="header-section-number">5.1.2</span> Contexte</h3>
<p>On s’intéresse au temps avant qu’un événement survienne. On observe chaque sujet jusqu’à ce que l’une des deux choses suivantes se produise : l’événement survient avant la fin de la période d’observation ou bien l’étude se termine et l’événement n’est toujours pas survenu. Dans l’exemple, l’événement correspond au fait d’interrompre son abonnement. On dispose donc d’une variable « temps », que l’on nomme <span class="math inline">\(T\)</span>, pour chaque individu qui est soit censurée soit non censurée. Si l’individu a expérimenté l’événement avant la fin de la période d’observation, la valeur de <span class="math inline">\(T\)</span> n’est pas censurée. Si l’événement n’est toujours pas survenu à la fin de la période d’observation, la valeur de <span class="math inline">\(T\)</span> est censurée. Pour chaque individu, on dispose également d’un ensemble de variables explicatives <span class="math inline">\(X_1, \ldots, X_p\)</span>. Pour l’instant, supposons que les valeurs de ces variables sont fixes dans le temps mais on reviendra plus loin au cas où leurs valeurs peuvent varier dans le temps. Bien que le terme analyse de survie semble implicitement référer à la santé, de nombreux autres exemples sont envisageables</p>
<ul>
<li>temps qu’un client demeure abonné à un service offert par notre compagnie.</li>
<li>temps de survie d’un individu après avoir été diagnostiqué avec un certain type de cancer.</li>
<li>ancienneté d’un travailleur au service d’une compagnie.</li>
<li>durée de vie d’une franchise.</li>
<li>temps avant la faillite d’une entreprise (ou d’un particulier).</li>
<li>temps avant le prochain achat d’un client.</li>
<li>temps durant lequel un(e) employé(e) est au chômage.</li>
</ul>
<p>Si aucune observation n’est censurée, c’est-à-dire, si on a observé le « vrai » temps pour chaque sujet, on pourrait alors simplement modéliser <span class="math inline">\(T\)</span> en incluant des covariables dans les paramètres de vraisemblance d’une loi positive (par exemple, avec une régression log-linéaire). En revanche, si des observations sont censurées dans l’échantillon, leur omission biaiserait l’analyse.</p>
<p>Ce chapitre se veut une introduction à l’analyse de données de survie. Comme le développement de la théorie de l’analyse de survie est assez complexe (plus encore que celle de la régression linéaire ou logistique), on s’intéressera ici uniquement aux principes de base afin d’être en mesure d’appliquer les méthodes et de bien interpréter les résultats. Plusieurs extensions sont également possibles. Un survol de ces dernières sera effectué dans des sections plus loin.</p>
<p>Il existe deux grandes approches pour analyser des données de survies :</p>
<ol type="i">
<li>nonparamétrique ou semi-paramétrique: estimateur de Kaplan–Meier, modèle de Cox (à risques proportionnels).</li>
<li>paramétrique : modèle paramétrique avec loi continue (Weibull, log-normal, log-logistique, gamma).</li>
</ol>
<p>Nous discuterons seulement de la première approche dans ce chapitre. Le tableau suivant fait une analogie entre ce que nous ferons dans ce chapitre et des méthodes que vous connaissez.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 33%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>réponse <span class="math inline">\(Y\)</span></th>
<th>résumé descriptif</th>
<th>comparaison de deux groupes</th>
<th>modèle général</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>continue</td>
<td>moyenne</td>
<td>test-<span class="math inline">\(t\)</span> pour deux échantillons</td>
<td>régression linéaire</td>
</tr>
<tr class="even">
<td>binaire</td>
<td>proportion</td>
<td>test d’indépendance du khi-deux</td>
<td>régression logistique</td>
</tr>
<tr class="odd">
<td>temps de survie (censure à droite)</td>
<td>fonction de survie temps de survie médian</td>
<td>test log-rang test de Wilcoxon généralisé (Gehan)</td>
<td>modèle de Cox</td>
</tr>
</tbody>
</table>
<p>La structure de données de base que l’on doit avoir pour travailler est la suivante:</p>
<ol type="1">
<li>une variable temps, <span class="math inline">\(T\)</span>.</li>
<li>une variable binaire <span class="math inline">\(C\)</span> (censure).</li>
<li>d’autres variables explicatives <span class="math inline">\(X_1, \ldots, X_p\)</span>, une par colonne.</li>
</ol>
</section>
</section>
<section id="fonctions-de-survie-et-de-risque" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="fonctions-de-survie-et-de-risque"><span class="header-section-number">5.2</span> Fonctions de survie et de risque</h2>
<p>Un des éléments de base d’une analyse de survie (<em>survival analysis</em>) est la <strong>fonction (ou courbe) de survie</strong>. Soit <span class="math inline">\(F(t)=\Pr(T \leq t)\)</span> la fonction de répartition du temps de survie <span class="math inline">\(t\)</span> et <span class="math inline">\(f(t) = \mathrm{d} / \mathrm{d} t F(t)\)</span>. La fonction de survie est <span class="math display">\[\begin{align*}
S(t)= \Pr(T &gt; t) = 1-F(t)
\end{align*}\]</span> et donne la probabilité que le temps de survie soit supérieur à <span class="math inline">\(t\)</span>. On verra plus loin comment estimer cette fonction avec un échantillon et comment tester l’égalité de deux (ou plusieurs) fonctions de survie.</p>
<p>La <strong>fonction de risque</strong> (en anglais, <em>hazard</em>) est <span class="math display">\[\begin{align*}
h(t) =  \frac{f(t)}{S(t)}
\end{align*}\]</span> où <span class="math inline">\(f(t)\)</span> est la fonction de densité (pour <span class="math inline">\(T\)</span> continu) ou de masse pour <span class="math inline">\(T\)</span> discret. Dans le cas discret où le temps peut seulement prendre les valeurs <span class="math inline">\(0, 1, 2, \ldots\)</span>, la fonction de risque est donc simplement la probabilité que l’événement survienne au temps <span class="math inline">\(t\)</span>, étant donné qu’il n’était pas survenu avant, <span class="math display">\[\begin{align*}
\Pr(T=t \mid T &gt; t) = \Pr(T=t) / \Pr(T &gt;t) = f(t)/S(t);
\end{align*}\]</span> c’est une probabilité conditionnelle. Dans le cas général, la fonction de risque est nécessairement positive mais peut prendre des valeurs supérieures à un. On ne peut donc pas, à strictement parler, la voir comme une probabilité et c’est pourquoi on parle plutôt de risque. En fait, cette fonction mesure le risque instantané que l’événement survienne au temps <span class="math inline">\(t\)</span>, étant donné qu’il n’était pas survenu avant.</p>
<p>Cette fonction est importante car il s’agit de celle que nous allons modéliser avec le modèle de régression de Cox. Si, en régression logistique, on modélise le logarithme des cotes, on modélise plutôt la fonction de risque en analyse de survie. Les fonctions de survie et de risque sont intimement reliées et <span class="math display">\[\begin{align*}
h(t) = - \frac{\mathrm{d} \ln\{S(t)\}}{\mathrm{d} t}, \qquad \qquad S(t) = \exp \left\{ -\int_0^t h(u) \mathrm{d} u\right\}.
\end{align*}\]</span> Ainsi, si on connaît la fonction de survie, on peut retrouver la fonction de risque et vice-versa. Par conséquent, un modèle pour la fonction de survie spécifie une fonction de risque (et vice-versa).</p>
</section>
<section id="estimation-dune-courbe-de-survie-et-de-risque" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="estimation-dune-courbe-de-survie-et-de-risque"><span class="header-section-number">5.3</span> Estimation d’une courbe de survie et de risque</h2>
<p>L’estimateur nonparamétrique le plus couramment utilisé pour l’estimation de la fonction de survie en présense de censure à droite est l’estimateur de Kaplan–Meier. De plus, cette méthode est nonparamétrique en ce sens qu’on ne suppose aucun modèle et qu’on suppose uniquement que la censure est non-informative.</p>
<p>Si l’échantillon ne contient aucune observation censurée (on a des temps exacts pour tous les sujets), l’estimateur de Kaplan–Meier de la fonction de survie à un temps <span class="math inline">\(t\)</span> donné est alors simplement la proportion des observations dans l’échantillon qui possède un temps de survie supérieur à <span class="math inline">\(t\)</span>. Par convention, on considère qu’une observation censurée à droite faisait partie de l’ensemble d’observations à risque au temps de censure observé.</p>
<p>On considère l’exemple des temps d’abonnement pour illustrer le concept. L’estimation de la fonction de survie selon la méthode Kaplan–Meier est obtenue grâce aux commandes suivantes:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(survie1, <span class="at">package =</span> <span class="st">"hecmulti"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimateur de Kaplan-Meier</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># La réponse "temps"est le temps de survie </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># et l'indicateur de censure "censure" est</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># "0" pour censuré à droite, "1" pour événement</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>kapm <span class="ot">&lt;-</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survfit</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">conf.type =</span> <span class="st">"log"</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> survie1)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kapm)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(kapm)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kapm, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"fonction de survie"</span>, </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"temps"</span>) </span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La fonction résumé (<code>summary</code>) renvoit l’estimation de la fonction de survie pour chaque temps d’échec (événement). La convention veut que la fonction escalier soit continue à gauche, limite à droite (caglad) et constante entre deux temps d’événements observés. Le <a href="#tbl-survie1-tableau" class="quarto-xref">Tableau&nbsp;<span>5.1</span></a> offre une sortie (tronquée) du résumé, modifié pour mieux illustrer les changements. L’estimation de la probabilité que le temps d’abonnement soit supérieur à 30 semaines est <span class="math inline">\(\widehat{S}(30)=0.986\)</span>.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-survie1-tableau" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-survie1-tableau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.1: Estimation de la fonction de survie (Kaplan–Meier) pour les données de survie d’abonnement.
</figcaption>
<div aria-describedby="tbl-survie1-tableau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">temps</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nb à risque</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nb échecs</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nb cumul.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">survie</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">erreur-type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.998</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">499</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.996</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14</td>
<td style="text-align: right;">498</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.994</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">497</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: right;">27</td>
<td style="text-align: right;">496</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: right;">29</td>
<td style="text-align: right;">495</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.988</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30</td>
<td style="text-align: right;">494</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: right;">34</td>
<td style="text-align: right;">493</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">189</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.028</td>
</tr>
<tr class="odd">
<td style="text-align: right;">202</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">332</td>
<td style="text-align: right;">0.170</td>
<td style="text-align: right;">0.039</td>
</tr>
<tr class="even">
<td style="text-align: right;">216</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">334</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-km-survie1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-km-survie1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-km-survie1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-km-survie1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Estimation de Kaplan–Meier de la fonction de survie pour les données d’abonnement avec intervalles de confiance ponctuels à 95%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>On peut également utiliser la fonction <code>quantile</code> pour obtenir une estimation des quartiles et un intervalle de confiance On utilise généralement le temps de survie médian (au lieu de la moyenne) dans ce type d’étude. Ici, l’estimé du temps de survie médian est de 114 semaines: on estime que la moitié des clients vont avoir une durée d’abonnement supérieure à 114 semaines. De même, la moitié des clients vont avoir une durée d’abonnement inférieure à 114 semaines. Un intervalle de confiance de niveau 95% pour ce temps médian est [<span class="math inline">\(110; 119\)</span>].</p>
<p>Un estimé de la moyenne et de l’écart-type est donné, mais ce dernier est biaisé (trop bas) puisque les données censurées ne donnent qu’une borne inférieure pour la vraie valeur. Avec un modèle paramétrique pour la survie (par ex., une loi exponentielle), les paramètres estimés du modèle dicteraient ces deux valeurs. Le modèle de Kaplan–Meier estime la survie, mais si la plus grande observation est censurée, la courbe n’atteindra pas zéro.</p>
<p>Le graphique de la fonction de survie permet de lire le temps de survie pour une probabilité donnée. Les bandes donnent un intervalle de confiance ponctuel de niveau 95% pour chaque temps donné.</p>
<p>Une information pertinente de la sortie est le nombre de données censurées: parmi les 500 observations, il y a 334 clients qui ont terminé leur abonnement et 166 qui sont censurées (le client est toujours abonné et le temps est donc une borne inférieure de la durée d’abonnement). Les données censurées contiennent moins d’information que les temps observés de défaillance puisqu’on sait uniquement la borne inférieure de la plage possible des valeurs pour le vrai temps de défaillance.</p>
<p>Les statistiques descriptives usuelles sont biaisées en raison de la censure. Avec l’estimateur de Kaplan–Meier, on peut aisément obtenir les quantiles. Si la courbe de survie estimée descend à zéro, il est également possible d’estimer la moyenne en calculant l’aire sous la courbe de survie.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Si la courbe ne descend pas à zéro, on obtient une borne inférieure (sous-estimation de la moyenne), appelée <em>moyenne restreinte</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(kapm, <span class="at">print.rmean =</span> <span class="cn">TRUE</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Par exemple, la moyenne estimée via Kaplan–Meier est 125 semaines (<code>rmean</code>), à comparer avec la moyenne empirique de <code>temps</code>, ici de 107.788 semaines, qui est biaisée.</p>
<section id="calcul-de-lestimateur-de-kaplanmeier" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="calcul-de-lestimateur-de-kaplanmeier"><span class="header-section-number">5.3.1</span> Calcul de l’estimateur de Kaplan–Meier</h3>
<p>Pour comprendre l’estimateur de Kaplan–Meier, il est utile de s’intéresser à sa construction. Deux éléments sont essentiels: on parle d’<strong>échec</strong> ou d’événement au temps <span class="math inline">\(t_i\)</span> si l’événement est observé (<span class="math inline">\(T_i=t_i\)</span>) au temps <span class="math inline">\(t_i\)</span>. Le nombre de <strong>personnes à risque</strong> au temps <span class="math inline">\(t_i\)</span> est le total des observations dont le temps mesuré excède <span class="math inline">\(t_i\)</span> (censure et événements postérieurs à <span class="math inline">\(t_i\)</span>)</p>
<p>Pour la <strong>construction</strong>, on procède comme suit:</p>
<ul>
<li>Ordonner les temps (uniques) où il y a des échecs (temps où <code>censure = 1</code>), disons <span class="math inline">\(t_{(1)} \leq \cdots \leq t_{(m)}\)</span></li>
<li>À chaque temps <span class="math inline">\(t_{(i)}\)</span> <span class="math inline">\((i=1, \ldots m)\)</span>, on calcule le nombre de personnes à risque, <span class="math inline">\(r_i\)</span>, et le nombre d’échecs, <span class="math inline">\(d_i\)</span>.</li>
<li>Le risque empirique est <span class="math inline">\(\widehat{h}_i = r_i/d_i\)</span>, la proportion d’échecs parmi les personnes à risque.</li>
</ul>
<p>L’estimateur de Kaplan–Meier définit une <strong>fonction escalier</strong></p>
<ul>
<li>Entre <span class="math inline">\(t=0\)</span> et <span class="math inline">\(t=t_{(1)}\)</span>, la survie est de 1.</li>
<li>Entre <span class="math inline">\(t=t_{(1)}\)</span> et <span class="math inline">\(t=t_{(2)}\)</span>, la survie est <span class="math inline">\(1-\widehat{h}_1\)</span>.</li>
<li>Entre <span class="math inline">\(t=t_{(2)}\)</span> et <span class="math inline">\(t=t_{(3)}\)</span>, la survie est <span class="math inline">\((1-\widehat{h}_1) \times (1-\widehat{h}_2)\)</span>, etc.</li>
</ul>
<p>Pour un temps <span class="math inline">\(t\)</span> donné, on multiplie tous les termes (<span class="math inline">\(1-\widehat{h}_i\)</span>) des temps d’échecs passés, <span class="math display">\[\begin{align*}
\widehat{S}(t) &amp;= \prod_{i: t_{(i)} &lt; t} \left( 1- \widehat{h}_i\right) \\ &amp;= \left( 1- \frac{d_1}{r_1}\right) \times \cdots \times \left( 1- \frac{d_{i(t)}}{r_{i(t)}}\right).
\end{align*}\]</span> où <span class="math inline">\(i(t) =\max(j \in \{1, \ldots, m\}:  t \geq t_{j})\)</span>, soit le plus grand indice parmi <span class="math inline">\(1, \ldots, m\)</span> tel que <span class="math inline">\(t \geq t_{i(t)}\)</span>. Par convention, si <span class="math inline">\(t &lt; t_{(1)}\)</span>, on fixe <span class="math inline">\(\widehat{S}(t)=1\)</span>. La fonction de survie n’est pas définie aux temps de défaillance observée, mais la convention veut qu’elle soit continue à gauche.</p>
<p>Ainsi, l’estimation de la survie estimée ne change qu’aux valeurs de <span class="math inline">\(t_{(i)}\)</span> (<span class="math inline">\(i=1, \ldots, m\)</span>). Les contre-marches de l’escalier ainsi défini interviennent uniquement aux temps observés d’échecs. Si à un moment donné toutes les personnes à risque expérimentent l’événement, la courbe descend à zéro. Si on a uniquement de la censure à droite, la courbe de survie n’atteindra jamais zéro si la plus grande observation est censurée à droite. Avec la troncation à gauche, la même logique s’applique mais les personnes ne sont à risque qu’à partir du temps minimum observé.</p>
</section>
</section>
<section id="comparaison-de-deux-courbes-de-survie" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="comparaison-de-deux-courbes-de-survie"><span class="header-section-number">5.4</span> Comparaison de deux courbes de survie</h2>
<p>Supposons que les individus ont été divisés en deux groupes et que <span class="math inline">\(S_1(t)\)</span> et <span class="math inline">\(S_2(t)\)</span> dénotent respectivement la fonction de survie du premier groupe et du deuxième groupe. On est souvent intéressé à tester l’égalité des fonctions de survie, c’est-à-dire, les hypothèses <span class="math inline">\(\mathscr{H}_0: S_1(t) = S_2(t)\)</span> pour tout <span class="math inline">\(t\)</span> et <span class="math inline">\(\mathscr{H}_1: S_1(t) \neq S_2(t)\)</span> pour au moins une valeur de <span class="math inline">\(t\)</span>.</p>
<p>Par exemple, dans une étude sur le temps de survie après avoir été diagnostiqué avec un certain type de cancer, on pourrait vouloir comparer le temps de survie des individus ayant reçu le traitement standard (groupe 1) au temps de survie des individus ayant reçu un nouveau traitement (groupe 2).</p>
<p>Les deux tests utilisés habituellement sont le test du log-rang (<em>log-rank test</em>) et le test de Wilcoxon généralisé (ou test de Gehan).</p>
<p>Testons l’hypothèse que la courbe de survie des clients masculins est la même que celle des clients féminins dans l’exemple des données d’abonnement:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>strat_sexe <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> sexe, <span class="at">data =</span> survie1)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lograng <span class="ot">&lt;-</span> <span class="fu">survdiff</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> sexe, <span class="at">data =</span> survie1)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Si on utilise les méthodes (<code>print</code>, <code>summary</code>, <code>plot</code>, <code>quantile</code>) pour la sortie de <code>survfit</code>, on obtiendra les résultats pour chaque strate (ou niveaux de la variable catégorielle). Par exemple, il y a 309 hommes et 191 femmes et l’estimation du temps de survie médian est de 110 semaines pour les hommes et de 123 semaines pour les femmes.</p>
<p>La fonction <code>survdiff</code> avec la formule retourne le résultat du test asymptotique du log-rang pour l’hypothèse d’égalité des fonctions de survie. La statistique du khi-deux vaut 16.43 et la valeur-<span class="math inline">\(p\)</span> du test est inférieure à <span class="math inline">\(10^{-4}\)</span>: on rejette donc <span class="math inline">\(\mathscr{H}_0\)</span> pour conclure qu’il y a donc une différence significative entre les deux courbes de survie.</p>
<p>Les courbes de survie selon le sexe sont représentées dans la <a href="#fig-survie-comparaison-courbes" class="quarto-xref">Figure&nbsp;<span>5.4</span></a>. On voit que la courbe des femmes est systématiquement au-dessus de celle des hommes. Les femmes ont donc tendance à rester abonnées plus longtemps que les hommes, et cette différence est significative.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> sexe, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> survie1), </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">FALSE</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"temps"</span>, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"fonction de survie"</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-survie-comparaison-courbes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-survie-comparaison-courbes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-survie-comparaison-courbes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-survie-comparaison-courbes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Courbes de survie pour les durées d’abonnement selon le sexe de l’individu.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Il est également possible de tester l’égalité des courbes de survie avec plus de deux groupes. Par exemple, s’il y a <span class="math inline">\(k\)</span> groupes, l’hypothèse nulle est alors <span class="math inline">\(\mathscr{H}_0: S_1(t)=S_2(t)=\cdots = S_k(t)\)</span> pour tout <span class="math inline">\(t\)</span>, versus l’alternative qu’au moins deux des fonctions ont une valeur différente pour au moins une valeur de <span class="math inline">\(t\)</span>; la loi nulle asymptotique du test est alors <span class="math inline">\(\chi^2_{k-1}\)</span>.</p>
<p>L’estimateur de Kaplan–Meier ne permet pas l’inclusion de variables explicatives à proprement parler: si on peut veut les différences au niveau de la survie selon les modalités d’une variable explicative catégorielle, on divise pour ce faire l’échantillon en sous-groupes et on utilise l’estimateur de Kaplan–Meier pour chacune des modalités en gardant en tête que cela réduit la taille de l’échantillon disponible et que l’estimation résultante est possiblement trop incertaine pour être utile.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
En résumé
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>L’analyse de survie est l’étude de temps d’attente (variable positive) avant que survienne un événement.</li>
<li>L’étude des temps de défaillance nécessite l’utilisation d’outils statistiques spécifiques en raison des mécanismes de censure et de troncation.</li>
<li>La fonction de survie <span class="math inline">\(S(t)\)</span> encode la probabilité que le temps de défaillance excède le temps <span class="math inline">\(t\)</span>.</li>
<li>La fonction de risque encode la probabilité de mourir au temps <span class="math inline">\(t\)</span> sachant qu’on a survécu jusque là.</li>
<li>La connaissance de la fonction de survie permet d’obtenir la fonction de risque et vice-versa.</li>
<li>Le mécanisme d’information partielle le plus courant en analyse de survie est la censure à droite (on ne connaît qu’une borne inférieure pour le temps de défaillance, l’événement n’étant toujours pas survenu au temps donné).</li>
<li>Si on traitait les temps de censure comme des temps de défaillance observée, on <em>sous-estimerait</em> la durée de survie.</li>
<li>L’estimateur de Kaplan–Meier est l’estimateur du maximum de vraisemblance nonparamétrique si on a de la censure à droite aléatoire ou non-informative. Il ne fait aucun postulat sur la distribution de la survie.</li>
<li>Pour que l’estimation soit de qualité, il faut un nombre <em>conséquent</em> d’observations (disons 1000). La quantité d’observations censurées impacte la précision de l’estimation.</li>
<li>L’estimateur est déficient si le plus grand temps observé est censuré à droite (l’estimation de la fonction de survie ne décroît pas à zéro).</li>
<li>Le test du log-rang permet de valider si deux fonctions de survie sont égales (en tout temps).</li>
<li>On peut estimer la fonction de survie indépendamment pour chaque modalité d’une variable explicative catégorielle en stratifiant: cela réduit la taille de l’échantillon pour chaque strate.</li>
<li>Le modèle de Kaplan–Meier ne permet pas d’estimer l’impact de variables explicatives sur la survie.</li>
</ul>
</div>
</div>
</section>
<section id="modèle-à-risques-proportionnels-de-cox" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="modèle-à-risques-proportionnels-de-cox"><span class="header-section-number">5.5</span> Modèle à risques proportionnels de Cox</h2>
<p>Le modèle à risques proportionnels de Cox (<em>proportional hazard model</em>) est l’un des modèles les plus utilisés pour l’analyse des données de survie.</p>
<section id="description-du-modèle-de-cox" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="description-du-modèle-de-cox"><span class="header-section-number">5.5.1</span> Description du modèle de Cox</h3>
<p>Soit <span class="math inline">\(h(t; \boldsymbol{x})\)</span> la valeur de la fonction de risque au temps pour un individu dont les valeurs des variables explicatives sont <span class="math inline">\(X_1=x_1, \ldots, X_p=x_p\)</span>. Le modèle à risques proportionnels est <span class="math display">\[\begin{align*}
h(t; \boldsymbol{x}) = h_0(t)\exp(\beta_1x_1 + \cdots + \beta_p x_p)
\end{align*}\]</span> où <span class="math inline">\(h_0(t)\)</span> est la fonction de risque de base; il n’est pas nécessaire de spécifier cette dernière, d’où la nature semiparamétrique du modèle de Cox. Le postulat de risques proportionnels implique que le terme de droite <span class="math inline">\(\exp(\mathbf{X}\boldsymbol{\beta})\)</span> ne dépend pas du temps, et plus particulièrement <span class="math inline">\(\beta_1, \ldots, \beta_p\)</span> ne varie pas en fonction de <span class="math inline">\(t\)</span>. Nous verrons subséquemment une extension pour accomoder ce cas de figure.</p>
<p>Lorsque toutes les variables explicatives prennent la valeur zéro, <span class="math inline">\(\boldsymbol{X}=\boldsymbol{0}\)</span>, on recouvre <span class="math inline">\(h(t; \boldsymbol{0})= h_0(t)\)</span>. Par conséquent, la fonction <span class="math inline">\(h_0(t)\)</span> peut être interprétée comme la fonction de risque lorsque toutes les variables explicatives valent zéro. Toutefois, tout comme la valeur de l’ordonnée à l’origine dans un modèle de régression linéaire, cette interprétation n’est pas nécessairement valide si la situation où toutes les variables explicatives valent zéro n’est pas possible ou si elle ne survient pas dans notre échantillon.</p>
<p>La deuxième partie du modèle, <span class="math inline">\(\exp(\beta_1x_1 + \cdots + \beta_p x_p)\)</span>, vient modéliser l’effet d’un changement des valeurs des variables explicatives sur la fonction de risque de base. Tout comme dans le cas de la régression logistique (l’effet des variables sur la cote), c’est un effet multiplicatif, d’où le terme <strong>risques proportionnels</strong>.</p>
<p>Pour l’interprétation des paramètres, il sera plus simple de penser en termes de rapport de risque (<em>hazard ratio</em>), qui est défini comme étant le rapport des fonctions de risque pour deux ensembles de valeurs des variables explicatives. Pour simplifier l’illustration, supposons que nous avons seulement une variable explicative <span class="math inline">\(X\)</span> et que <span class="math inline">\(h(t; x) = h_0(t)\exp(\beta x)\)</span>. Le rapport de risque lorsque <span class="math inline">\(X=x_1\)</span> par rapport à <span class="math inline">\(X=x_0\)</span> est <span class="math display">\[\begin{align*}
\frac{h(t; x_1)}{h(t; x_0)} = \exp\{\beta(x_1-x_0)\}.
\end{align*}\]</span> Par conséquent, l’impact d’une augmentation de <span class="math inline">\(X\)</span> d’une unité (quand <span class="math inline">\(x_1-x_0=1\)</span>) est <span class="math inline">\(\exp(\beta)\)</span>. Ainsi, pour chaque augmentation d’une unité pour <span class="math inline">\(X\)</span>, le risque que l’événement survienne est multiplié par <span class="math inline">\(\exp(\beta)\)</span>.</p>
<p>Le terme <strong>risques proportionnels</strong> fait référence à la situation où le rapport de risque dépend seulement de la différence <span class="math inline">\(x_1-x_0\)</span> et non pas du temps lui-même. Le rapport de risque est constant par rapport au temps <span class="math inline">\(t\)</span>. Cela implique que l’effet d’une variable est stable dans le temps. Nous verrons plus loin comment faire en sorte que l’effet d’une variable puisse varier dans le temps.</p>
<p>Débutons avec un exemple simple en utilisant les données d’abonnement: on ajuste un modèle de Cox en utilisant seulement la variable binaire sexe.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cox1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> sexe, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie1,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients, tests et IC 95% de Wald</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox1)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Test du rapport de vraisemblance</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(cox1, <span class="at">type =</span> <span class="dv">3</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La sortie inclut notamment des tests de significativité globale basés sur la vraisemblance comparant le modèle sans variable explicative avec celui ajusté (rapport de vraisemblance, score et Wald). Ces trois statistiques ciblent la même hypothèse, aussi on peut ne s’attarder qu’au test du rapport de vraisemblance, qui est plus fiable et généralement plus puissant. Le tableau des coefficients donne les estimations <span class="math inline">\(\widehat{\beta}\)</span>. Le rapport de risque pour <code>sexe=1</code> versus <code>sexe=0</code> est <span class="math inline">\(\exp(\widehat{\beta})\)</span>, tandis qu’on obtiendrait le rapport de risque pour <code>sexe=0</code> versus <code>sexe=1</code>, soit <span class="math inline">\(\exp(-\widehat{\beta})\)</span>. Les statistiques de test et la valeur-<span class="math inline">\(p\)</span> associée sont basées sur la statistique de Wald, soit <span class="math inline">\(\widehat{\beta}/\mathsf{se}(\widehat{\beta})\)</span>, tandis que les intervalles de confiance à 95% pour le rapport de risque sont des intervalles de Wald de la forme <span class="math inline">\(\exp\{\widehat{\beta} \pm 1.96 \cdot \mathsf{se}(\widehat{\beta})\}\)</span> pour le rapport de risque. Un rapport de risque de 1 signifie que le risque n’est pas affecté par la variable explicative. Ici, le test correspondant à l’hypothèse nulle <span class="math inline">\(\beta=0\)</span> ne mène pas au rejet de l’hypothèse qui veut que la variable n’impacte pas le risque. On pourrait obtenir les intervalle</p>
<div class="cell" data-layout-align="center">
<div id="tbl-cox1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.2: Rapport de risques et intervalles de confiance de Wald à niveau 95%.
</figcaption>
<div aria-describedby="tbl-cox1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne inf.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.79</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Il y a une seule variable explicative, le sexe de l’individu. L’estimation du paramètre de l’effet de sexe est -0.47. Ce paramètre est significativement différent de <span class="math inline">\(0\)</span> (valeur-<span class="math inline">\(p\)</span> du test du rapport de vraisemblance inférieure à <span class="math inline">\(10^{-10}\)</span>). Pour l’interprétation, on utilise la colonne <code>exp(coef)</code> qui contient la valeur <span class="math inline">\(\exp(\hat{\beta}_{\texttt{sexe}}) = \exp(-0.466) = 0.628\)</span>. Ainsi, le rapport du risque d’une femme par rapport à un homme est <span class="math display">\[\begin{align*}
\frac{\hat{h}(t; \texttt{sexe}=1)}{\hat{h}(t; \texttt{sexe}=0)}= 0.628.
\end{align*}\]</span> Par conséquent, le risque qu’une femme interrompe son abonnement est 0.628 fois celui d’un homme. Une femme est donc moins à risque de quitter qu’un homme. Nous avions déjà vu cela à la section précédente lorsque nous avions comparé les courbes de survie des hommes et des femmes. Il est important de se rappeler qu’avec ce modèle, l’effet d’une variable est le même dans le temps (peu importe la valeur de <span class="math inline">\(t\)</span>). Donc, une femme est moins à risque de quitter qu’un homme à tout moment, d’après ce modèle. Inversement, le ratio du risque d’un homme par rapport à une femme est <span class="math inline">\(\exp(-\hat{\beta}_{\texttt{sexe}}) = 1/0.628=1.59\)</span>. Ainsi, à tout moment, un homme a un risque d’interrompre son abonnement qui est 59% plus élevé que celui d’une femme.</p>
<p>Comme il y a un seul paramètre ici, les tests basés sur la vraisemblance pour <span class="math inline">\(\mathscr{H}_0: \boldsymbol{\beta}=\boldsymbol{0}\)</span> reviennent à tester l’effet de la variable sexe. Le test de Wald est le même que celui du tableau des coefficients. Dans le cas particulier où il y a une seule variable explicative catégorielle comme ici, le test du score est équivalent au test du log-rang que nous avons vu à la section précédente à une petite différence près lorsqu’il y a des doublons (ex aequo) dans les temps de survie.</p>
<p>On pourrait également utiliser une variable explicative continue plutôt qu’une variable binaire; le principe est le même.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cox2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> age, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie1,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox2)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Le rapport de risque pour âge est 0.959 et donc le risque diminue de 4.1% chaque fois que l’âge augmente d’un an — le risque d’interrompre l’abonnement diminue lorsque l’âge augmente et cet effet est significatif (valeur-<span class="math inline">\(p\)</span> du test de significativité globale inférieures à <span class="math inline">\(10^{-4}\)</span>).</p>
<p>Généralement, on considérera le modèle de Cox avec toutes les variables explicatives simultanément. La variable <span class="math inline">\(\texttt{region}\)</span> est nominale tandis que la variable <span class="math inline">\(\texttt{service}\)</span> est ordinale (avec quatre modalités). Nous allons les incorporer, comme d’habitude, en utilisant des variables indicatrices avec <span class="math inline">\(\texttt{region=1}\)</span> et <span class="math inline">\(\texttt{service=0}\)</span> (le client n’est abonné à aucun autre service) comme catégories de référence.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(survie1, <span class="fu">table</span>(service))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cox3 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                age <span class="sc">+</span> sexe <span class="sc">+</span> region <span class="sc">+</span> service, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie1, </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox3)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Effets de type 3 </span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># (modèle avec toutes les variables sauf une)</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(cox3, </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">type =</span> <span class="dv">3</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-survie5-coefs" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-survie5-coefs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.3: Rapport de risque et intervalles de confiance à niveau 95% de Wald pour le modèle de Cox de base avec toutes les variables explicatives.
</figcaption>
<div aria-describedby="tbl-survie5-coefs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne inf.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region2</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">region3</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">1.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region4</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">1.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">region5</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">1.37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service1</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.45</td>
</tr>
<tr class="even">
<td style="text-align: left;">service2</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service3</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.19</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-survie5-deviance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-survie5-deviance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.4: Tests du rapport de vraisemblance pour les effets de type III pour le modèle de Cox avec toutes les variables explicatives.
</figcaption>
<div aria-describedby="tbl-survie5-deviance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistique</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ddl</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">valeur-p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">68.07</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">32.82</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">&lt;0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region</td>
<td style="text-align: right;">7.67</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: right;">159.31</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">&lt;0.0001</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Les effets des variables sont maintenant des effets marginaux. Ainsi, lorsque les autres variables demeurent fixes, le risque de quitter d’une femme est 0.511 fois plus petit que celui d’un homme. L’effet marginal (une fois que les autres variables sont incluses) de la variable sexe est significatif (valeur-<span class="math inline">\(p\)</span> inférieure à <span class="math inline">\(10^{-4}\)</span>).</p>
<p>Toutes autres choses étant égales, chaque augmentation de l’âge d’un an fait diminuer le risque d’interrompre l’abonnement. Plus précisément, le risque est multiplié par 0.95 lorsque l’âge augmente d’un an et cet effet est significatif.</p>
<p>Pour la variable service, l’interprétation se fait par rapport à la catégorie de référence, qui est la catégorie <span class="math inline">\(\texttt{0}\)</span> (abonné à aucun autre service). Ainsi, si le client est abonné à un autre service, son risque de quitter est 0.353 fois celui d’un client qui n’est pas abonné à un autre service (toutes autres choses étant égales). Si le client est abonné à deux autres services, son risque de quitter est encore plus petit comparativement à un client qui n’est pas abonné à un autre service (rapport de risque de 0.174) Finalement, si le client est abonné à trois autres services, son risque de quiter est encore plus petit (rapport de risque de 0.115). Les paramètres de ces trois variables sont tous significatifs. Ainsi, les clients qui sont abonnés à un, deux ou trois services ont un risque de quitter qui est significativement plus faible que celui d’un client qui n’est pas abonné à un autre service. Le tableau d’analyse de déviance (effets de type 3) donne les statistiques du rapport de vraisemblance pour tester globalement la significativité d’une variable explicative modélisée avec plusieurs indicatrices. Pour la variable <span class="math inline">\(\texttt{service}\)</span>, le test présenté teste l’hypothèse nulle <span class="math inline">\(\mathscr{H}_0: \beta_{\texttt{service}_1}=\beta_{\texttt{service}_2}=\beta_{\texttt{service}_3}=0\)</span> contre l’alternative qu’un moins un de ces trois paramètres est non-nul. Le test est largement significatif (statistique du rapport de vraisemblance valant 159.31 avec une valeur-<span class="math inline">\(p\)</span> inférieure à <span class="math inline">\(10^{-4}\)</span>). L’effet de la variable <span class="math inline">\(\texttt{service}\)</span> est donc globalement significatif. Afin de comparer les autres modalités entre elles, par exemple afin de voir si le risque de quitter est différent entre un client qui a deux services et un autre qui a trois services, il suffit de changer la catégorie de référence à la commande <code>class</code> et de réajuster le modèle.</p>
<p>Finalement, la variable <span class="math inline">\(\texttt{region}\)</span> n’est pas globalement significative (statistique du rapport de vraisemblance de 7.67 avec une valeur-<span class="math inline">\(p\)</span> de 0.1 basée sur la loi asymptotique <span class="math inline">\(\chi^2_4\)</span>).</p>
</section>
<section id="estimation-de-la-fonction-de-survie-pour-des-valeurs-particulières-des-variables-explicatives" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="estimation-de-la-fonction-de-survie-pour-des-valeurs-particulières-des-variables-explicatives"><span class="header-section-number">5.5.2</span> Estimation de la fonction de survie pour des valeurs particulières des variables explicatives</h3>
<p>Il est possible d’obtenir l’estimation de la fonction de survie pour des valeurs particulières des variables explicatives. Pour ce faire, il faut avoir un autre fichier de données qui contient les valeurs des variables explicatives pour lesquelles on veut une estimation de la fonction de survie. Si on ajuste le modèle avec aucune variable explicative, on retrouvera alors l’estimation de Kaplan–Meier de la fonction de survie.</p>
<p>Supposons qu’on ajuste le modèle avec les variables sexe et âge seulement dans l’exemple du temps d’abonnement, et que l’on désire la fonction de survie pour les hommes de 25 et 60 ans et pour les femmes de 25 et 60 ans. Le fichier <code>survie2</code> contient les données qui seront utilisées à cette fin.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-courbes-survie" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-courbes-survie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-courbes-survie-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-courbes-survie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Courbes de survies du modèle de Cox pour les quatre profils client.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Les quatre fonctions de la <a href="#fig-courbes-survie" class="quarto-xref">Figure&nbsp;<span>5.5</span></a> correspondent aux profils pour lesquels nous désirons une estimation de la courbe de survie. La courbe 1 est pour les hommes de 25 ans, la courbe 2 pour les femmes de 25 ans, la courbe 3 pour les hommes de 60 ans et la courbe 4 pour les femmes de 60 ans. On voit donc que, parmi ces quatre profils, les hommes de 25 ans sont le plus à risque de quitter tandis que les femmes de 60 ans sont le moins à risque de quitter.</p>
</section>
<section id="variables-explicatives-dont-la-valeur-change-dans-le-temps" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="variables-explicatives-dont-la-valeur-change-dans-le-temps"><span class="header-section-number">5.5.3</span> Variables explicatives dont la valeur change dans le temps</h3>
<p>Il est clair que certaines caractéristiques d’un individu évoluent dans le temps (<em>time-varying covariates</em>). Si le sexe d’un individu est stable dans le temps, son revenu, son statut matrimonial, l’endroit où il habite, sont par contre des caractéristiques qui peuvent changer dans le temps. Il peut alors être intéressant d’en tenir compte dans l’analyse. Rappelez-vous que le modèle à risques proportionnels est <span class="math display">\[\begin{align*}
h(t; \boldsymbol{x}) = h_0(t) \exp(\beta_1x_1 + \cdots + \beta_px_p).
\end{align*}\]</span></p>
<p>Supposons que la variable <span class="math inline">\(X_1\)</span> change au fil du temps et que les autres demeurent fixes. On peut alors réécrire le modèle <span class="math display">\[\begin{align*}
h(t; \boldsymbol{x}) = h_0(t) \exp\{\beta_1x_1(t) + \cdots + \beta_px_p\},
\end{align*}\]</span> où <span class="math inline">\(x_1(t)\)</span> indique que la valeur de <span class="math inline">\(X_1\)</span> dépend du temps <span class="math inline">\(t\)</span>.</p>
<p>Supposons que la variable <span class="math inline">\(\texttt{service}\)</span>, qui représente le nombre d’autres services souscrits, est la seule que nous voulons modéliser comme une variable qui varie dans le temps. Pour l’âge, nous prenons simplement l’âge au début de l’abonnement, idem pour la région.</p>
<p>Le plus difficile est de créer correctement le fichier de données pour effectuer ce genre d’analyse. Pour chaque personne, on peut identifier plusieurs moments où l’une ou l’autres des valeurs des variables explicatives change. Supposons qu’on a observé un événement au temps <span class="math inline">\(t_1\)</span>, et que la valeur de la covariable change à <span class="math inline">\(t_0\)</span>, où <span class="math inline">\(0 &lt; t_0 &lt; t_1\)</span>. On peut envisager cette observation donne deux contributions: une pour la trajectoire sur l’intervalle <span class="math inline">\((0, t_0]\)</span> (censure à droite) et l’autre, après la modification, sur l’intervalle <span class="math inline">\((t_0, t_1]\)</span> (troncature à gauche). Puisque la valeur est observée passée le premier intervalle, on a besoin de l’information sur toute la fenêtre (les deux bornes) et le type d’événement pour la première fenêtre sera de la censure à droite.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lexischtemps" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lexischtemps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Lexis_censure_modif.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:35.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lexischtemps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Diagramme de Lexis avec trajectoires. Pour ajuster le modèle, on peut casser la contribution d’une observation en segments: considérons un seul changement survenant au temps <span class="math inline">\(t_c\)</span>. Pour le premier segment, on enregistre <span class="math inline">\(t_c\)</span> comme valeur maximale (censure à droite), tandis que pour la deuxième portion, l’observation est tronquée à gauche à partir de <span class="math inline">\(t_c\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>La base de données <code>survie3</code> contient le format adéquat: une colonne <code>evenement</code> qui indique la censure (tout intervalle intermédiaire pour un individu est traité comme de la censure à droite) et les bornes de la fenêtre, <code>debut</code> et <code>fin</code>. Dans cet exemple, il y a eu au plus un changement dans la variable <span class="math inline">\(\texttt{service}\)</span>, comme présenté dans le fichier <code>survie3</code>. Les variables explicatives <span class="math inline">\(\texttt{age}\)</span>, <span class="math inline">\(\texttt{sexe}\)</span> et <span class="math inline">\(\texttt{region}\)</span> sont comme précédemment.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-survie3-donnees" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-survie3-donnees-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.5: Aperçu des cinq premières observations de la base de données <code>survie3</code>.
</figcaption>
<div aria-describedby="tbl-survie3-donnees-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">id</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">debut</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fin</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">evenement</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sexe</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">region</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">service</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">178</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>On regarde plus en détail le profil des cinq premiers clients présenté dans le <a href="#tbl-survie3-donnees" class="quarto-xref">Tableau&nbsp;<span>5.5</span></a>, dont seuls deux ont changé le nombre d’abonnements; les individus 3–5 se sont désabonnés du service cellulaire à un moment donné. Le premier client était abonné à deux autres services au début de son abonnement au téléphone cellulaire mais, après 130 semaines d’abonnement, a effectué un changement à son forfait pour ne conserver qu’un autre service en plus du cellulaire. Pour le deuxième client, comme <span class="math inline">\(\verb+temps_ch+\)</span> est manquante, il est toujours abonné à deux autres services et ce, jusqu’à la fin de l’étude.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(survie3, <span class="at">package =</span> <span class="st">"hecmulti"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cox4 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time =</span> debut, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">time2 =</span> fin, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">event =</span> evenement) <span class="sc">~</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                age <span class="sc">+</span> sexe <span class="sc">+</span> region <span class="sc">+</span> service, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie3)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>L’interprétation se fait comme précédemment; on a omis l’option <code>ties = "exact"</code> parce que cette option est trop gourmande en calcul. Puisque c’est la valeur d’une variable qui varie dans le temps et non pas son effet, on a l’interprétation usuelle. Par exemple, le risque de quitter pour un client qui a un autre service est 0.601 fois celui d’un client qui n’a aucun autre service (référence). Le fait d’avoir deux ou trois services diminue encore plus le risque de quitter (rapports de risque de 0.265 et 0.209, respectivement).</p>
</section>
<section id="postulat-de-risques-proportionnels" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="postulat-de-risques-proportionnels"><span class="header-section-number">5.5.4</span> Postulat de risques proportionnels</h3>
<p>Le modèle de Cox fait l’hypothèse que la fonction de risque de base est identique peut importe la valeur des variables catégorielles. La <a href="#fig-risquepropfig" class="quarto-xref">Figure&nbsp;<span>5.7</span></a> illustre à quoi ce postulat correspond dans un cas simple où il y a uniquement une variable binaire explicative.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-risquepropfig" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-risquepropfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-risquepropfig-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-risquepropfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Courbes de risques proportionnelles (panneau supérieur) et non proportionnelles (panneau inférieur) avec rapport de risque et fonctions de survie correspondantes.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Si ce n’est pas le cas, alors les résultats du modèle ne sont pas nécessairement fiables.Comme pour un modèle de régression, il est possible de créer des résidus du modèles et de faire des graphiques diagnostics pour potentiellement infirmer le postulat de risques proportionnels <span class="citation" data-cites="Grambsch.Therneau:1994">(<a href="references.html#ref-Grambsch.Therneau:1994" role="doc-biblioref">Grambsch and Therneau 1994</a>)</span>. Si l’hypothèse tient la route, alors il ne devrait pas y avoir de tendance temporelle dans les résidus.</p>
<p>La commande <code>cox.zph</code> permet de tester le postulat de risques proportionnels à l’aide d’un test du score pour voir si la pente <span class="math inline">\(\beta(t)\)</span> associée à une covariable est constante en fonction du temps <span class="math inline">\(t\)</span> pour tout temps; si la valeur-<span class="math inline">\(p\)</span> est grande, cela indique une absence de preuve contre l’hypothèse nulle <span class="math inline">\(\mathscr{H}_0\)</span>: <span class="math inline">\(\{\beta(t)=c\)</span> pour tout <span class="math inline">\(t\}\)</span>. La fonction <code>plot</code> permet également d’obtenir un graphique des résidus en fonction du temps.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-coxphhypothese" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coxphhypothese-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-coxphhypothese-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coxphhypothese-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Estimations des coefficients en fonction du temps basés sur les moindres carrés pondérés (diagnostic graphique de Grampsch et Therneau).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-coxphhypothese" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coxphhypothese-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.6: Postulat de risques proportionnels: test du score de Grampsch et Therneau (1994) pour les coefficients constants dans le temps et valeur-p asymptotique basée sur la loi nulle khi-deux.
</figcaption>
<div aria-describedby="tbl-coxphhypothese-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">effet</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ddl</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">valeur-p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">0.040</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">0.291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region</td>
<td style="text-align: right;">3.81</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.432</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: right;">10.97</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.012</td>
</tr>
<tr class="odd">
<td style="text-align: left;">global</td>
<td style="text-align: right;">21.23</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">0.012</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Dans la <a href="#fig-coxphhypothese" class="quarto-xref">Figure&nbsp;<span>5.8</span></a>, on voit que le coefficient pour service augmente au fil du temps pour tous les groupes. On pourrait capturer cette interaction ou stratifier pour calculer le risque selon le nombre de services, au risque d’avoir trop peu d’observations pour estimer de manière fiable le risque de base. C’est explicable par le fait que les personnes avec plus de services tendent à avoir une survie plus longue.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>diag_risqueprop <span class="ot">&lt;-</span> <span class="fu">cox.zph</span>(cox3)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(diag_risqueprop)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(diag_risqueprop)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Si le postulat n’est pas validé, on peut interpréter l’effet comme un rapport de risque moyen pondéré sur la période de suivi, mais ce dernier change selon le moment <span class="citation" data-cites="Stensrud.Hernan:2020">(<a href="references.html#ref-Stensrud.Hernan:2020" role="doc-biblioref">Stensrud and Hernán 2020</a>)</span>. Cela implique également que les erreurs-types associées aux estimations sont trompeuses. La section suivante permettra de généraliser le modèle de Cox et traiter ce cas de figure.</p>
</section>
<section id="stratification" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="stratification"><span class="header-section-number">5.5.5</span> Stratification</h3>
<p>Une manière de modéliser la non-proportionnalité pour une variable catégorielle est par la stratification. Supposons que nous avons une variable explicative catégorielle <span class="math inline">\(Z=1, \ldots, K\)</span> pour lequel le postulat de risque proportionnels n’est pas valide. On s’intéresse à l’effet des variables <span class="math inline">\(\mathbf{X}\)</span>. Typiquement, on ne s’intéresse pas directement à l’effet de la variable <span class="math inline">\(Z\)</span>. Le modèle de Cox avec stratification (pour la variable <span class="math inline">\(Z\)</span>) est <span class="math display">\[\begin{align*}
h(t; \mathbf{x}, z=k) = h_k(t) \exp(\boldsymbol{\beta} \mathbf{x}),
\end{align*}\]</span> où <span class="math inline">\(h_k(t)\)</span> est la fonction de risque de base quand <span class="math inline">\(Z=k\)</span> (<span class="math inline">\(k=1, \ldots, K\)</span>). L’effet des autres variables explicatives <span class="math inline">\(\mathbf{X}\)</span> est supposé être le même peut importe la valeur de <span class="math inline">\(Z\)</span>, mais la fonction de risque de base peut différer. Le rapport de risque pour <span class="math inline">\(Z=k\)</span> versus <span class="math inline">\(Z=j\)</span> est <span class="math inline">\(h_k(t)/h_j(t)\)</span>; cette quantité dépend du temps <span class="math inline">\(t\)</span>, mais pas des autres caractéristiques mesurées par <span class="math inline">\(\mathbf{X}\)</span>. L’effet de la variable est donc variable dans le temps (et non pas constant). Ce modèle permet donc de modéliser la non-proportionnalité pour la variable <span class="math inline">\(Z\)</span>. Si on stratifie par rapport à une variable, il ne faut pas l’inclure dans le modèle en plus car elle est déjà modélisée via la stratification. Notez que les paramètres <span class="math inline">\(\boldsymbol{\beta}\)</span> seront estimés à l’aide des données de toutes les strates, mais les fonctions de risque <span class="math inline">\(h_k(t)\)</span> seront obtenues à l’aide des sous-échantillons correspondant aux valeurs de <span class="math inline">\(Z\)</span>.</p>
<p>L’avantage de la stratification est que cette méthode permet de modéliser n’importe quel changement dans l’effet d’une variable dans le temps sans devoir spécifier un type de changement particulier, comme lorsqu’on doit choisir la forme de l’interaction.Il est important de comprendre qu’on ne pourra pas estimer l’effet de la variable de stratification comme d’ordinaire en étudiant le coefficient <span class="math inline">\(\beta\)</span> associé. On perd la possibilité de tester l’effet de la variable de stratification et on réduit la taille de l’échantillon pour l’estimation de la fonction de risque de base. On devrait principalement utiliser la stratification seulement avec des variables pour lesquelles nous n’avons pas besoin d’estimer l’effet (variables secondaires ou de contrôles).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Stratification par service</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cox7 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(temps, <span class="dv">1</span><span class="sc">-</span>censure) <span class="sc">~</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                age <span class="sc">+</span> sexe <span class="sc">+</span> <span class="fu">strata</span>(service), </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie1)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Décompte par région</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(survie1, <span class="fu">table</span>(service)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox7)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-cox-stratif" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-stratif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.7: Rapport de risques et intervalles de confiances à niveau 95% pour le modèle de Cox stratifié par service.
</figcaption>
<div aria-describedby="tbl-cox-stratif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne inf.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.85</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>On voit à la lecture de la sortie dans le <a href="#tbl-cox-stratif" class="quarto-xref">Tableau&nbsp;<span>5.7</span></a> qu’il n’y a plus de paramètres pour la variable <code>service</code>. Les paramètres des autres variables s’interprètent comme d’habitude. On peut néanmoins résumer l’information pour <code>service</code> en calculant une statistique descriptive, par exemple les différences de survie à des temps donnés.</p>
<p>La <a href="#fig-courbesurviesstrat" class="quarto-xref">Figure&nbsp;<span>5.9</span></a> illustre l’effet de la stratification sur l’estimation du risque de base et des courbes de survie. On voit que la résolution des courbes est moindre, puisque chaque fonction est estimée à partir d’un sous-ensemble des données.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-courbesurviesstrat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-courbesurviesstrat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-courbesurviesstrat-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-courbesurviesstrat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Courbes de survie estimées par nombre de service pour le modèle de Cox avec stratification pour un homme de 40 ans.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="modèle-non-proportionnel" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="modèle-non-proportionnel"><span class="header-section-number">5.5.6</span> Modèle non-proportionnel</h3>
<p>Pour simplifier l’exposition, supposons que nous avons une seule variable explicative <span class="math inline">\(X\)</span>. L’équation du modèle à risques proportionnels est <span class="math inline">\(h(t; x) = h_0(t)\exp(\beta x)\)</span> et suppose que la fonction de risque de base <span class="math inline">\(h_0(t)\)</span> est indépendante de la variable explicative <span class="math inline">\(X\)</span>. Une manière de modéliser la non-proportionnalité est d’inclure un terme d’interaction entre la variable et le temps. Il existe plusieurs façons de le faire. Par exemple, on pourrait inclure une nouvelle variable qui est le produit entre le temps et la variable <span class="math inline">\(X\)</span>. Le modèle est alors <span class="math display">\[\begin{align*}
h(t; x) = h_0(t) \exp(\beta_1x + \beta_2xt).
\end{align*}\]</span> Pour ce modèle, le rapport de risque, pour une augmentation d’une unité de <span class="math inline">\(X\)</span> est <span class="math inline">\(\exp(\beta_1+ \beta_2t)\)</span> et dépend du temps <span class="math inline">\(t\)</span>: c’est un modèle avec risques non proportionnels. On retombe sur le modèle à risques proportionnels lorsque <span class="math inline">\(\beta_2=0\)</span>.</p>
<p>Supposons que l’effet du nombre de service augmente avec le temps. On peut inclure à la fois <code>service</code>, qui capture l’effet au temps zéro, et le surenchérissement ou la diminution à mesure que le temps d’abonnement progresse.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer variables binaires par service</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>survie1_modif <span class="ot">&lt;-</span> survie1 <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">service1 =</span> service <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">service2 =</span> service <span class="sc">==</span> <span class="dv">2</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">service3 =</span> service <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>cox_np <span class="ot">&lt;-</span> survival<span class="sc">::</span><span class="fu">coxph</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>     age <span class="sc">+</span> sexe <span class="sc">+</span> service <span class="sc">+</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">tt</span>(service1) <span class="sc">+</span> <span class="fu">tt</span>(service2) <span class="sc">+</span> <span class="fu">tt</span>(service3), </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> survie1_modif, </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">tt =</span> <span class="cf">function</span>(x, t, ...){t <span class="sc">*</span> x})</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Le bloc code précédent illustre comment créer le terme non proportionnel: on spécifie avec l’option <code>tt()</code> la variable qui change dans le temps et on spécifie par la suite la nature de l’interaction temporelle en définissant une fonction <code>tt</code>.</p>
<p>Les variables catégorielles n’étant pas supportées en l’état, elles doivent préalablement être transformées en variable indicatrices binaires. Une fois les nouvelles variables dans la base de données, on procède à la spécification du terme de risque non proportionnel.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-coxnph" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coxnph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.8: Rapport de risque et intervalles de confiance à niveau 95% pour le modèle à risques non proportionnels (interaction linéaire entre temps et service).
</figcaption>
<div aria-describedby="tbl-coxnph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">test de Wald</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">valeur-p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">-7.37</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.543</td>
<td style="text-align: right;">-5.24</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service1</td>
<td style="text-align: right;">0.144</td>
<td style="text-align: right;">-4.29</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">service2</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">-3.76</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service3</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">-4.14</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">tt(service1)</td>
<td style="text-align: right;">1.010</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: left;">0.0298</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tt(service2)</td>
<td style="text-align: right;">1.010</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: left;">0.1132</td>
</tr>
<tr class="even">
<td style="text-align: left;">tt(service3)</td>
<td style="text-align: right;">1.023</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: left;">0.0133</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Le <a href="#tbl-coxnph" class="quarto-xref">Tableau&nbsp;<span>5.8</span></a> contient les résultats. Les coefficients pour l’interaction avec <span class="math inline">\(t\)</span> sont petits, mais c’est parce que la variable temps n’est pas standardisée et qu’elle s’étend de 0 à 200 semaines: de petites variations sont possiblement importantes quand le temps augmente. Les estimations des coefficients pour l’interaction sont tous positifs, ce qui suppose que le risque augmente avec le temps. Si on considère comme source plausible d’effet du nombre de services un quelconque rabais, il semble que cet effet protecteur s’amenuise. Deux des termes d’interaction sont significatifs à niveau 5% (statistiques de Wald <span class="math inline">\(Z\)</span> de 2.173, 1.584 et 2.476 et valeurs-<span class="math inline">\(p\)</span> correspondantes de 0.03, 0.113 et 0.013).</p>
<p>On peut aussi utiliser la structure de modèle à risques non-proportionnels pour capturer l’effet des changements qui interviennent au sein de variables explicatives dans le temps. Par exemple, l’âge de la personne (en années) augmente à mesure que le temps d’abonnement (en semaines) passe, d’où <span class="math inline">\(\texttt{age}(t) = \texttt{age} + t/52\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># interaction entre service et temps</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># objet avec 'tt' varie dynamiquement</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cox6 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">tt</span>(age) <span class="sc">+</span> sexe <span class="sc">+</span> service, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> survie1, </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">tt =</span> <span class="cf">function</span>(x, t, ...){x <span class="sc">+</span> t<span class="sc">/</span><span class="dv">52</span>})</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox6)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On inclut uniquement la variable transformée <code>tt(age)</code> et son effet est toujours fortement significatif pour expliquer le désabonnement potentiel: les personnes plus âgées sont moins susceptibles de résilier leur abonnement.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cox_np <span class="ot">&lt;-</span> survival<span class="sc">::</span><span class="fu">coxph</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Surv</span>(temps, censure) <span class="sc">~</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">tt</span>(age) <span class="sc">+</span> sexe <span class="sc">+</span> service, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> survie1, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">tt =</span> <span class="cf">function</span>(x, t, ...){x <span class="sc">+</span> t<span class="sc">/</span><span class="dv">52</span>})</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox_np)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On spécifie avec l’option <code>tt()</code> dans la formule la variable qui change dans le temps et par la suite la nature de l’interaction temporelle avec l’argument <code>tt</code>.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-cox-np" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-np-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.9: Rapport de risque et intervalles de confiance à niveau 95% pour le modèle à risques non proportionnels (interaction linéaire entre temps et âge).
</figcaption>
<div aria-describedby="tbl-cox-np-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne inf.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">tt(age)</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">region2</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">1.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region3</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">1.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">region4</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">1.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region5</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">1.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">service1</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service2</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">service3</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>L’interaction employée ici n’est pas la seule fonction du temps qu’on pourrait spécifier: on pourrait par exemple inclure une fonction de type escalier <span class="math inline">\(\mathrm{I}(T&lt; t_0)\)</span> qui indique que l’effet de la variable disparaît après le temps <span class="math inline">\(t_0\)</span>, si par exemple un rabais disparaît après une certaine durée d’abonnement, avec <code>rabais * I(t&lt;t0)</code> pour une valeur numérique <code>t0</code> fixée.</p>
</section>
</section>
<section id="modèle-à-risques-compétitifs" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="modèle-à-risques-compétitifs"><span class="header-section-number">5.6</span> Modèle à risques compétitifs</h2>
<p>Parfois, la raison pour laquelle un individu quitte l’état étudié peut avoir un intérêt en soi. Par exemple si on s’intéresse au temps qu’un employé demeure au service de la compagnie, la distinction entre le fait qu’il ait démissionné ou bien qu’il ait été renvoyé peut avoir un impact sur l’effet des variables explicatives. Comme autre exemple, si on s’intéresse au temps de survie d’un individu après qu’il ait été diagnostiqué avec un certain type de cancer, il pourrait être important de distinguer selon la cause exacte de la mort.</p>
<p>De manière générale, supposons qu’il y a <span class="math inline">\(K\)</span> manières possibles que l’événement survienne.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-transitionetat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-transitionetat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/transition_etats_modele_risque_competitifs.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-transitionetat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.10: Schéma illustrant la transition entre état de base et autres événements compétitifs.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Dans notre exemple d’abonnement cellulaire, supposons que nous avons trois causes possibles pour la perte d’un client: soit il a interrompu son abonnement pour aller chez le compétiteur A, soit pour aller chez le compétiteur B, soit il n’a plus de cellulaire du tout. On considère un modèle avec transition d’un état de base (abonné) vers un état absorbant (désabonnement, soit chez compétiteur <span class="math inline">\(A\)</span>, compétiteur <span class="math inline">\(B\)</span> ou abandon du cellulaire).</p>
<p>On a deux avenues pour l’estimation de ce type de modèle: soit on ajuste un modèle de Kaplan–Meier, soit un modèle de Cox.</p>
<p>On peut alors spécifier <span class="math inline">\(K\)</span> fonctions de risques (une pour chaque manière) et obtenir le modèle de Cox à risques compétitifs (<em>competing risks</em>), <span class="math display">\[\begin{align*}
h_1(t; \boldsymbol{x})&amp;= h_{01}(t) \exp(\beta_{11}x_1 + \cdots + \beta_{p1} x_p)\\
&amp;\vdots\\
h_K(t; \boldsymbol{x})&amp;= h_{0K}(t) \exp(\beta_{1K}x_1 + \cdots + \beta_{pK} x_p)\\
\end{align*}\]</span> Notez que les coefficients sont différents d’une équation à l’autre. En estimant ce modèle, on obtient donc une estimation de l’effet des variables selon la raison du départ de l’état. De plus, on peut aussi inclure des variables dont la valeur change dans le temps, comme vu précédemment.</p>
<p>Ce qui simplifie énormément la situation est qu’il est prouvé qu’on peut estimer les paramètres de chaque équation séparément sans perte de précision. Par conséquent, en pratique, il suffira d’ajuster <span class="math inline">\(K\)</span> modèles de Cox séparément.</p>
<p>Les données pour cet exemple se trouvent dans le fichier <code>survie4</code>. La seule nouveauté par rapport au fichier original est la variable <span class="math inline">\(\texttt{censure}\)</span> qui est maintenant codée ainsi</p>
<ul>
<li>1, si le temps est censuré (l’individu est toujours abonné à notre service)</li>
<li>2, si l’individu a quitté pour aller chez le compétiteur A</li>
<li>3, si l’individu a quitté pour aller chez le compétiteur B</li>
<li>4, si l’individu a quitté parce qu’il n’a plus besoin de cellulaire.</li>
</ul>
<p>On peut calculer la fréquence de chaque modalité avec <code>table</code>. Ainsi, il y a donc 166 clients toujours abonnés, 170 qui nous ont quitté pour aller chez A, 121 pour aller chez B, et 43 qui n’ont plus de cellulaires.</p>
<p>Pour ajuster le modèle lorsque la cause du départ est le compétiteur A, le code définit <code>censure == 2</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rappel pour `event`:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   1 pour observation, </span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   0 pour censure à droite</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># On utilise la convention TRUE = 1, FALSE = 0</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(survie4, <span class="at">package =</span> <span class="st">"hecmulti"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>cox5 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(<span class="at">time =</span> temps, </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">event =</span> censure <span class="sc">==</span> <span class="dv">2</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">type =</span> <span class="st">"right"</span>) <span class="sc">~</span> </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                age <span class="sc">+</span> sexe <span class="sc">+</span> region <span class="sc">+</span> service, </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> survie4,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox5)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-cox-risquecompetA" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-risquecompetA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;5.10: Rapport de risque et intervalles de confiance à niveau 95% pour le modèle à risques compétitifs (probabilité de quitter pour compétiteur A).
</figcaption>
<div aria-describedby="tbl-cox-risquecompetA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">terme</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">exp(coef)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne inf.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">borne sup.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexe</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region2</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">region3</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">1.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region4</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">1.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">region5</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">1.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service1</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">service2</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">service3</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.22</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Notez qu’on précise que les valeurs 1, 3 et 4 sont des observations censurées. Ici, l’événement d’intérêt est que le client est parti chez le compétiteur A. S’il est toujours abonné (<span class="math inline">\(\texttt{censure=1}\)</span>), s’il est parti chez le compétiteur B (<span class="math inline">\(\texttt{censure=3}\)</span>) ou s’il nous a quitté car il n’a plus de cellulaire (<span class="math inline">\(\texttt{censure=4}\)</span>), alors l’événement « quitter pour aller chez A » n’est pas survenu. C’est pourquoi on doit traiter ces situations comme des censures.</p>
<p>Ainsi, on voit que l’événement est survenu 170 fois et qu’il y a 330 censures. L’interprétation des paramètres se fait comme précédemment. Sauf qu’il faut préciser qu’il s’agit du risque de quitter pour aller chez le compétiteur A. Par exemple, le risque de quitter pour aller chez le compétiteur A d’une femme est 0.444 fois le risque de quitter pour aller chez le compétiteur A d’un homme. Ainsi, les femmes sont moins à risque de quitter pour aller chez le compétiteur A que les hommes.</p>
<p>Dans <strong>R</strong>, on peut aussi ajuster simultanément tous les modèles en spécifiant que l’événement d’intérêt est un facteur: c’est alors la catégorie de référence qui fait foi de l’état de départ. Il faut également une variable qui identifie l’observation — dans le cas qu’on considère, c’est simplement une colonne avec des valeurs de <span class="math inline">\(1\)</span> à <span class="math inline">\(n\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>rc_cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">Surv</span>(<span class="at">time =</span> temps, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">event =</span> <span class="fu">factor</span>(censure)) <span class="sc">~</span> sexe <span class="sc">+</span> age <span class="sc">+</span> service,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> survie4 <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(survie4)),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> id)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On obtient l’ensemble des coefficients dans le tableau résumé, un pour chaque événement compétitif autre que la référence.</p>
<p>Si on voulait ajuster le modèle de Kaplan–Meier, pour une transition d’un état de base (abonné) vers un état dit absorbant (désabonnement, soit chez compétiteur A ou B ou abandon du cellulaire), il faut obligatoirement ajuster toutes les courbes simultanément. On ajustera le modèle multi-état en spécifiant un facteur pour l’événement, où encore une fois la catégorie de référence est abonnement (<code>censure=1</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rc_km <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(<span class="at">time =</span> temps, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">event =</span> <span class="fu">factor</span>(censure)) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> survie4)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Les représentations graphiques pour le modèle à risque compétitif sont légèrement différente. Si on dichotomise l’événement d’intérêt (survie ou échec), il y a deux options possibles et la probabilité d’échec est complémentaire à la survie. Avec plus d’un choix, on obtiendra un graphique avec une estimation de la probabilité pour chaque modalité de l’événement: la <a href="#fig-competitif" class="quarto-xref">Figure&nbsp;<span>5.11</span></a> montre ceci pour la sortie du modèle de Cox et le modèle de Kaplan–Meier en ajoutant la courbe correspondant à la probabilité de demeurer abonné.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-competitif" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-competitif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="survie_files/figure-html/fig-competitif-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-competitif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.11: Probabilité d’événement sans variable explicative (Kaplan-Meier, gauche) et avec âge, service et sexe (modèle de Cox, droite).
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf">vignette</a> du paquet <code>survival</code> offre des détails sur l’implémentation des méthodes qui traitent de l’inclusion de variables explicatives dont la valeur change dans le temps et sur les risques compétitifs.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
En résumé
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Le modèle de Cox suppose qu’on peut diviser le risque en deux parties: le risque de base <span class="math inline">\(h_0(t)\)</span> commun à tou(te)s (composante nonparamétrique) et l’effet multiplicatif <span class="math inline">\(\exp(\mathbf{X}\boldsymbol{\beta})\)</span> (composante paramétrique)</li>
<li>Puisque la fonction de risque de base est commune à toutes les observations, moins d’incertitude sur l’estimation de la survie.</li>
<li>L’impact sur la survie de changement dans les variables explicatives n’est pas multiplicatif.</li>
<li>Le modèle de Cox suppose que le rapport de cote ne dépend pas du temps (postulat de risques proportionnels).</li>
<li>On peut vérifier ce postulat et généraliser le modèle au besoin.</li>
<li>Plutôt que d’inclure une variable catégorielle, on peut utiliser la stratification pour estimer le risque de base séparément sur chaque sous-groupe.</li>
<li>le modèle à risques non-proportionnels permet d’inclure une interaction entre le temps et une avec variable ou un coefficient.</li>
<li>Si les variables explicatives changent au fil du temps, on peut décomposer la contribution de l’observation en plusieurs segments.</li>
<li>Il y a un lien possible avec le modèle à risque proportionnels si l’effet est le même pour tous (comme l’âge).</li>
<li>Le modèle multi-état (modèle à risques compétitifs) permet d’estimer la probabilité de chaque transition: la survie pour l’événement de base reste le même (désabonnement), mais on décompose la probabilité de la censure selon les différents événements compétitifs.</li>
</ul>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Grambsch.Therneau:1994" class="csl-entry" role="listitem">
Grambsch, Patricia M., and Terry M. Therneau. 1994. <span>“<span class="nocase">Proportional hazards tests and diagnostics based on weighted residuals</span>.”</span> <em>Biometrika</em> 81 (3): 515–26. <a href="https://doi.org/10.1093/biomet/81.3.515">https://doi.org/10.1093/biomet/81.3.515</a>.
</div>
<div id="ref-Stensrud.Hernan:2020" class="csl-entry" role="listitem">
Stensrud, Mats J., and Miguel A. Hernán. 2020. <span>“<span class="nocase">Why Test for Proportional Hazards?</span>”</span> <em>JAMA</em> 323 (14): 1401–2. <a href="https://doi.org/10.1001/jama.2020.1267">https://doi.org/10.1001/jama.2020.1267</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Si on considère une variable aléatoire positive, alors l’aire sous la courbe de survie donne l’espérance.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/lbelzile\.github\.io\/math60602\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./reglogistique.html" class="pagination-link" aria-label="Régression logistique">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Régression logistique</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./analysefactorielle.html" class="pagination-link" aria-label="Réduction de la dimension">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Réduction de la dimension</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Tous droits réservés (Denis Larocque, Léo Belzile)</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lbelzile/math60602/edit/master/survie.qmd" class="toc-action"><i class="bi bi-github"></i>Éditer cette page</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>